### PR TITLE
Expose setCurrentCaptions method from native SDKs

### PR DESCRIPTION
**Pull request by arsimr16**
* now you can tell the player to use a specific captions track from the
playlistItem.tracks array or turn off captions by setting the index to 0
* this is useful when implementing custom player controls

* index 0 - turns off captions
* index 1 - use the first item in the tracks array
* index 2 - use the second item in the tracks array
* etc. (if there is no item in the tracks array to match, captions are turned off)

* for some reason iOS behaves differently from Android and requires that
you add 1 to the index (e.g. to use the track at index 0 in the tracks
array, the argument should be set to 2 instead of 1 like on Android)
* to make the behavior consistent on the React Native side, I just add 1
to the setCurrentCaptions call in ios/RNJWPlayerManager.m

### CODE REVIEW

**Comment by chaimPaneth** [comment]
I will check out the setCurrentCaptions index issue on iOS that it doesn't work when passing value 0 this seems funky to me.

**Comment by arsimr16** [comment]
Awesome, let me know what you find out!

**Comment by BrettBlox** [comment]
Having the ability to use our custom controls to toggle captions on/off is essential for the release of our app. This PR seems to be exactly what we need. Any updates on when/if this will be merged?

**Comment by arsimr16** [comment]
@chaimPaneth I fixed the merge conflicts.  Let me know if there's anything else you'd like me to do to make this ready to be merged.

**Comment by chaimPaneth** [comment]
Hi @arsimr16 

I added this in version 0.2.11

Thank you very much,
Chaim

**Pull request closed without merging**
