### PR TITLE
Fixes #283 and adds option to hide multiple ui groups in android (#284)

### LINKED ISSUE #283: onFullScreen and onFullScreenExit work fine on Android but do not work on iOS
onFullScreen and onFullScreenExit work fine on Android but do not work on iOS. anyone can help please?
thank you!

```
<JWPlayer
      onLayout={onLayout}
      ref={ref}
      key={tag}
      style={[{ flex: 1 }, style]}
      config={{
        license: Platform.select({ ios: IOS_API_KEY, android: ANDROID_API_KEY }),
        backgroundAudioEnabled: true,
        portraitOnExitFullScreen: true,
        landscapeOnFullScreen: true,
        fullScreenOnLandscape: true,
        ...props.config,
      }}
      {...newProps}
      onPlayerError={(e) => {
        console.log(e.nativeEvent);
        alert(e.nativeEvent?.error || 'Player Error.');
      }}
      onFullScreen={(e) => {
        console.log(e, 'on full screen');
      }}
      onFullScreenExit={(e) => {
        console.log(e, 'on full screen exit');
      }}
/>
```

```
"react": "18.2.0"
"react-native": "0.71.3"
"react-native-jw-media-player": "^0.2.35"

### PR DESCRIPTION
**Pull request by nateshmbhat**
PR summary : 
 - fixes #283 
 - implements #284 and updates doc

Hide ui groups usage : 

```ts
<JWPlayer
        config={{
          ...
          hideUIGroups: ['casting_menu', 'settings_menu']
}}
```

### CODE REVIEW

**Comment by nateshmbhat** [comment]
@chaimPaneth can you please review and merge this ?

**Comment by chaimPaneth** [comment]
Hi @nateshmbhat 

Thank you for all your contributions! :-) Can you kindly separate the fix for #283 and the code for hiding multiple ui groups, as I mentioned in the #283 issue I still need to get more info from JW on it.

Thanks again.

**Comment by nateshmbhat** [comment]
sure , will seperate the PR

**Comment by nateshmbhat** [comment]
also can u please help me with this issue ? #256

**Comment by nateshmbhat** [comment]
@chaimPaneth have reverted delegate method removal

**Review by chaimPaneth — APPROVED** [review]

**Comment by grigdodon** [comment]
is this available on the latest 0.2.35 version?

**Pull request merged**
