### PR TITLE
Adds caption support

### LINKED ISSUE #92: Closed Captions Support
Hi there, I couldn't find any documentation about closed captioning support.
Does the `mediaId` property allow the player to read the captions available?

Any assistance on this topic would be appreciated, thank you.

### PR DESCRIPTION
**Pull request by archcorsair**
Resolves #92 

- Adds Closed Captioning Support
- Ability to pass [tracks](https://sdk.jwplayer.com/ios/v3/reference/Classes/JWTrack.html) in [playlistItem](https://sdk.jwplayer.com/ios/v3/reference/Classes/JWPlaylistItem.html)

### CODE REVIEW

**Comment by chaimPaneth** [comment]
Hi @archcorsair 

Thank you for this will you be adding the changes for android as well?

**Comment by archcorsair** [comment]
@chaimPaneth I will try my best. I am not familiar with objective-c or java. I learned it for this task

**Comment by archcorsair** [comment]
@chaimPaneth I've added the changes to android as well

**Comment by chaimPaneth** [comment]
Thank you very much.

**Pull request merged**
