### PR TITLE
Android build fix: change jCenter() >> mavenCentral()

### PR DESCRIPTION
**Pull request by KestasVenslauskas**
Fixed android project build.
I think I will try to contribute a bit more for android and react side of this project so this PR is just to be able to build android project with all the required dependencies for project.

### CODE REVIEW

**Comment by chaimPaneth** [comment]
Hi @KestasVenslauskas 

Can you kindly resubmit the PR with only the changes in the build.gradle as it's the only changes necessary for clean builds.

Thank you very much for your contributions.

**Comment by KestasVenslauskas** [comment]
How do you actually run the android project on IDE without errors?
Because this devDependency downloads required node_modules for development.
It downloads all react packages as well because when you open android project on Android Studio it should find react & other linked libraries and SDK's under node_modules folder. Maybe there is a command to download peerDependencies that I don't know of?

**Comment by KestasVenslauskas** [comment]
@chaimPaneth Any feedback on my last comment? As I see there is no other way to get react-native inside node modules without this.

**Comment by chaimPaneth** [comment]
Don't you start your projects with the installation of react-native? We're assuming here that the project you're using this library in has installed react-native.

We can add it in devDependecies; no harm but not sure it's required, what's your take?

**Comment by KestasVenslauskas** [comment]
I'm not talking about react-native CLI.
When you create a project there is an android folder same as in this library.
Which contains gradle files and it points react-native dependency inside node_modules folder.
Here
[            url "$rootDir/../node_modules/react-native/android"](https://github.com/chaimPaneth/react-native-jw-media-player/blob/e3ada42f895477e4fa349bf0bb7451a148e420dc/android/build.gradle#L45)
And here
https://github.com/chaimPaneth/react-native-jw-media-player/blob/e3ada42f895477e4fa349bf0bb7451a148e420dc/android/build.gradle#L51

So when you build android project it takes react-native (.aar or .jar) from node_modules

**Comment by chaimPaneth** [comment]
Closing in favor of https://github.com/chaimPaneth/react-native-jw-media-player/releases/tag/0.2.19

**Pull request closed without merging**
