### PR TITLE
Fix/android chromecast

### PR DESCRIPTION
**Pull request by Jmilham21**
### This PR does:
- Fixes / implements a workaround for Android Chromecast issues. 
- Fixes a session bug after initial reconfiguration. 
-- Removes `MediaButtonReceiver` from manifest as it's legacy code

### Why this is necessary:
Intended to address this #314 issue

### Additional information:
See my comment on the above issue for more context.

### CODE REVIEW

**Comment by tara-singh-danu** [comment]
@Jmilham21 There is no Chromecast icon visible on the player to cast the video.

**Comment by Jmilham21** [comment]
> @Jmilham21 There is no Chromecast icon visible on the player to cast the video.

@tara-singh-danu there has been a change in implementation of the cast module before the creation of this PR. By default, the bridge won't import the cast SDK. Follow the instructions in the updated [README](https://github.com/chaimPaneth/react-native-jw-media-player/blob/523431353b8c5d1d5993a38dcf85f97e4e145b6d/README.md) found on this PR to enable casting.

**Comment by tara-singh-danu** [comment]
@Jmilham21 Followed each and every step mentioned in the readme still not getting cast icon.
Screenshot 2024-02-08 at 10 43 04 PM

**Comment by Jmilham21** [comment]
The Example app in the project should work out of the box. Are you sure you are using the right branch? It works for me with no issues and multiple devices. 

The device you are testing with may be incompatible with casting. You can check with the following Java code
`boolean isCastApiAvailable = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(context) == ConnectionResult.SUCCESS;`

**Comment by tara-singh-danu** [comment]
@Jmilham21 I tried to run the android app on this branch(fix/android-chromecast) the app is not crashing and the icon is there but after casting the video, video is not playing on Chromecast device.
I tested Youtube Chromecast is working on the phone and the Chromecast device.

**Comment by Jmilham21** [comment]
@tara-singh-danu This [commit](https://github.com/chaimPaneth/react-native-jw-media-player/pull/340/commits/523431353b8c5d1d5993a38dcf85f97e4e145b6d) fixed the issue you are describing. If this change is implemented, the mismatch session IDs between sender and receiver should be resolved.

If it continues, check the logcat for anything interesting. Also, when testing with Chromecast, I highly recommend creating your own custom/styled receiver so you can [inspect the web console. ](https://developers.google.com/cast/docs/debugging/remote_debugger)

**Comment by paulrinaldi** [comment]
Could this be reviewed? @chaimPaneth 

Is there any idea when a release may have this incorporated?

**Review by chaimPaneth — APPROVED** [review]

**Comment by fdobre** [comment]
Is there any way to hide the cast icon completely for Android?

`hideUiGroup: 'casting_menu'`, or  `hideUiGroups[ 'casting_menu']` or `RNJWPlayerUseGoogleCast = false` in gradle file do not seem to work for Android.

**Pull request merged**
